require("teddytrombone.core.keymaps")
require("teddytrombone.core.options")
require("teddytrombone.core.autocmds")
require("teddytrombone.core.lazy")
-- require("teddytrombone.core.lsp")
require("teddytrombone.core.typoscript")
